import Layout from '@/app/twitter/components/layout/layout'
import './twitter.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function TwitterLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='justify-center flex'>

      <Layout>{children}</Layout>
    </div>
  )
}
